services:
  express:
    build:
      context: .
      dockerfile: dev.dockerfile
    tty: true  # keep container running
    working_dir: /workspace/express
    volumes:
      - ./:/workspace/express
    ports:
      - 80:3000

  mysql:
    image: mysql
    working_dir: /var/lib/mysql
    volumes:
      - ./.mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
